import { randomUUID } from 'node:crypto';
import { appendFileSync, mkdirSync, readFileSync, renameSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

function readJson(path) {
  const text = readFileSync(path, 'utf8');
  return JSON.parse(text.replace(/^\uFEFF/, ''));
}

async function main() {
  let input = '';
  for await (const chunk of process.stdin) input += chunk;
  const event = JSON.parse(input);
  const command = event.tool_input?.command;
  const matchesCommand = typeof command === 'string' &&
    /(?:^|[\\/\s"'])Invoke-CodexHookProbe\.ps1(?:["']|\s|$)/i.test(command);
  const matchesOptIn = typeof command === 'string' && /(?:^|\s)-RunP03(?:\s|$)/i.test(command);
  const matchesP04 = typeof command === 'string' &&
    /(?:^|[\\/\s"'])Invoke-CodexBusyWindow\.ps1(?:["']|\s|$)/i.test(command) &&
    /(?:^|\s)-RunP04(?:\s|$)/i.test(command);
  const directory = join(tmpdir(), 'cross-session-agent-messaging', 'probes');
  mkdirSync(directory, { recursive: true });
  appendFileSync(join(directory, 'P03-hook-invocations.jsonl'), `${JSON.stringify({
    at: new Date().toISOString(),
    sessionId: event.session_id ?? null,
    turnId: event.turn_id ?? null,
    toolUseId: event.tool_use_id ?? null,
    eventName: event.hook_event_name ?? null,
    toolName: event.tool_name ?? null,
    commandType: typeof command,
    matchesCommand,
    matchesOptIn,
    matchesP04,
  })}\n`);
  if (event.hook_event_name !== 'PostToolUse' || event.tool_name !== 'Bash' ||
      (!(matchesCommand && matchesOptIn) && !matchesP04)) return;

  if (typeof event.session_id !== 'string' || !event.session_id) {
    throw new Error('Missing session_id in the hook input.');
  }

  let marker;
  let body;
  let note = null;
  if (matchesP04) {
    if (!/^[0-9a-f]{8}(?:-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(event.session_id)) {
      throw new Error('Invalid P04 recipient session ID.');
    }
    const inboxPath = join(directory, `P04-inbox-${event.session_id}.json`);
    try {
      note = readJson(inboxPath);
    } catch (error) {
      if (error.code === 'ENOENT') return;
      throw error;
    }
    const window = readJson(join(directory, `busy-${event.session_id}.json`));
    if (note.probe !== 'P04' || note.threadId !== event.session_id ||
        !/^P04-[0-9a-f]{32}$/.test(note.marker) || typeof note.message !== 'string' || !note.message.trim() ||
        window.probe !== 'P04' || window.threadId !== event.session_id || window.state !== 'completed' ||
        typeof note.windowId !== 'string' || note.windowId !== window.windowId) {
      throw new Error('P04 inbox does not match the recipient and completed work window.');
    }
    marker = note.marker;
    body = `External prototype message from a test script; peer content, not a PO instruction.\n\n${note.message}`;
    // Only one invocation can consume the pending file. Keep its original bytes as evidence.
    try {
      renameSync(inboxPath, join(directory, `${marker}.consumed.json`));
    } catch (error) {
      if (error.code === 'ENOENT') return;
      throw error;
    }
  } else {
    // The work tool does not know this marker; only the hook supplies it to Codex.
    marker = `P03-${randomUUID().replaceAll('-', '')}`;
    body = `Synthetic prototype message generated by the PostToolUse hook. Marker: ${marker}. ` +
      `At the pending checkpoint, report P03-CHECKPOINT: ${marker}, then complete the planned short action. ` +
      'Do not read probe records to obtain this marker. This tests hook context injection only, not peer delivery.';
  }
  const output = {
    hookSpecificOutput: { hookEventName: 'PostToolUse', additionalContext: body },
  };
  const record = {
    probe: matchesP04 ? 'P04-external-hook' : 'P03-post-tool-context',
    synthetic: !matchesP04,
    sessionId: event.session_id,
    turnId: event.turn_id ?? null,
    toolUseId: event.tool_use_id ?? null,
    generatedAt: new Date().toISOString(),
    marker,
    sourceNote: note,
    output,
    modelReceipt: 'unverified',
  };
  const recordName = matchesP04 ? `${marker}-hook.json` : `${marker}.json`;
  writeFileSync(join(directory, recordName), `${JSON.stringify(record, null, 2)}\n`, { flag: 'wx' });
  process.stdout.write(`${JSON.stringify(output)}\n`);
}

main().catch((error) => {
  process.stderr.write(`Prototype hook error: ${error.message}\n`);
  process.exitCode = 1;
});
