import { randomUUID } from 'node:crypto';
import { appendFileSync, mkdirSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

async function main() {
  let input = '';
  for await (const chunk of process.stdin) input += chunk;
  const event = JSON.parse(input);
  const command = event.tool_input?.command;
  const matchesCommand = typeof command === 'string' &&
    /(?:^|[\\/\s"'])Invoke-CodexHookProbe\.ps1(?:["']|\s|$)/i.test(command);
  const matchesOptIn = typeof command === 'string' && /(?:^|\s)-RunP03(?:\s|$)/i.test(command);
  const directory = join(tmpdir(), 'cross-session-agent-messaging', 'probes');
  mkdirSync(directory, { recursive: true });
  appendFileSync(join(directory, 'P03-hook-invocations.jsonl'), `${JSON.stringify({
    at: new Date().toISOString(),
    sessionId: event.session_id ?? null,
    turnId: event.turn_id ?? null,
    toolUseId: event.tool_use_id ?? null,
    eventName: event.hook_event_name ?? null,
    toolName: event.tool_name ?? null,
    commandType: typeof command,
    matchesCommand,
    matchesOptIn,
  })}\n`);
  if (event.hook_event_name !== 'PostToolUse' || event.tool_name !== 'Bash' ||
      !matchesCommand || !matchesOptIn) return;

  if (typeof event.session_id !== 'string' || !event.session_id) {
    throw new Error('Missing session_id in the hook input.');
  }

  // The work tool does not know this marker; only the hook supplies it to Codex.
  const marker = `P03-${randomUUID().replaceAll('-', '')}`;
  const body = `Synthetic prototype message generated by the PostToolUse hook. Marker: ${marker}. ` +
    `At the pending checkpoint, report P03-CHECKPOINT: ${marker}, then complete the planned short action. ` +
    'Do not read probe records to obtain this marker. This tests hook context injection only, not peer delivery.';
  const output = {
    hookSpecificOutput: { hookEventName: 'PostToolUse', additionalContext: body },
  };
  const record = {
    probe: 'P03-post-tool-context',
    synthetic: true,
    sessionId: event.session_id,
    turnId: event.turn_id ?? null,
    toolUseId: event.tool_use_id ?? null,
    generatedAt: new Date().toISOString(),
    marker,
    output,
    modelReceipt: 'unverified',
  };
  writeFileSync(join(directory, `${marker}.json`), `${JSON.stringify(record, null, 2)}\n`, { flag: 'wx' });
  process.stdout.write(`${JSON.stringify(output)}\n`);
}

main().catch((error) => {
  process.stderr.write(`P03 hook error: ${error.message}\n`);
  process.exitCode = 1;
});
