import { execFile } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { promisify, parseArgs } from 'node:util';
import { BridgeStore, handleHook, readJson, renderPeer, wakeText } from './store.mjs';
import { cliPath, commandString, repoRoot } from './entry.mjs';

const execute = promisify(execFile);
const directory = fileURLToPath(new URL('.', import.meta.url));
const usage = 'Use one of: install, register, pair, send, reply, status, hook.';

const HOOK_EVENTS = [
  { event: 'PostToolUse', options: { additionalContextLimit: 20000 } },
  { event: 'UserPromptSubmit', options: { additionalContextLimit: 20000 } },
  { event: 'Stop', options: {} },
];

// Recognizes this product's hook (and the retired prototype's) so installs stay
// idempotent across reinstalls and location changes without touching other tools.
const isBridgeHook = (hook) => typeof hook?.command === 'string' &&
  /(?:bridge[\\/]+cli\.mjs|Bridge\.mjs)"\s+hook$/i.test(hook.command.trim());

function installHooks(hooksFile) {
  const bridgeCommand = `${commandString()} hook`;
  let config = { description: 'ClaudeToCodex cross-session bridge hooks. Generated by `bridge install`.', hooks: {} };
  if (existsSync(hooksFile)) {
    config = readJson(hooksFile);
    if (typeof config !== 'object' || config === null) throw new Error('Existing hooks file is not a JSON object.');
    config.hooks ??= {};
  }
  for (const { event, options } of HOOK_EVENTS) {
    const existing = Array.isArray(config.hooks[event]) ? config.hooks[event] : [];
    const kept = existing.filter((group) => !(Array.isArray(group?.hooks) && group.hooks.some(isBridgeHook)));
    kept.push({ hooks: [{ type: 'command', command: bridgeCommand, timeout: 5, async: false, ...options }] });
    config.hooks[event] = kept;
  }
  mkdirSync(dirname(hooksFile), { recursive: true });
  writeFileSync(hooksFile, `${JSON.stringify(config, null, 2)}\n`);
  console.log(`Hooks file: ${hooksFile}`);
  console.log(`Bridge hook command: ${bridgeCommand}`);
  console.log('Manual steps that cannot be automated:');
  console.log('  1. In the Codex session run /hooks, review and trust the three new bridge hook definitions (a changed definition invalidates its trust hash and must be re-trusted).');
  console.log('  2. Hooks are not hot-loaded: fully exit the running Codex session, then `codex resume <threadId>` to reload with the new hooks.');
  console.log('  3. Claude-side inbound policy: crossSessionInbound holds foreign messages for approval by default; `accept` is the verified configuration. This product never changes that setting.');
}

async function main() {
  const { positionals, values } = parseArgs({
    allowPositionals: true,
    options: {
      codex: { type: 'string' }, 'claude-endpoint': { type: 'string' },
      body: { type: 'string' }, 'body-file': { type: 'string' }, to: { type: 'string' },
      'hooks-file': { type: 'string' },
    },
  });
  const [command] = positionals;
  if (positionals.length !== 1) throw new Error(usage);
  const store = new BridgeStore();
  if (command === 'hook') {
    let input = '';
    for await (const chunk of process.stdin) input += chunk;
    process.stdout.write(`${JSON.stringify(handleHook(store, JSON.parse(input)))}\n`);
    return;
  }
  if (command === 'install') {
    installHooks(values['hooks-file'] ? resolve(values['hooks-file']) : join(repoRoot(), '.codex', 'hooks.json'));
    return;
  }
  if (command === 'register') {
    store.initialize();
    const result = await execute('powershell.exe', [
      '-NoProfile', '-File', join(directory, 'delivery', 'Register-ClaudeEndpoint.ps1'),
      '-Directory', join(store.root, 'endpoints'),
    ], { windowsHide: true, timeout: 15000 });
    process.stdout.write(`${result.stdout.trim()}\n`);
    return;
  }
  if (command === 'pair') {
    if (!values.codex || !values['claude-endpoint']) throw new Error('pair requires --codex and --claude-endpoint.');
    console.log(JSON.stringify(store.pair(values.codex, values['claude-endpoint']), null, 2));
    return;
  }
  if (command === 'status') {
    const pair = store.getPair();
    const pendingPath = join(store.root, 'pending', pair.codexId, 'message.json');
    const pending = existsSync(pendingPath) ? readJson(pendingPath) : null;
    const eventPath = join(store.root, 'events.jsonl');
    const events = existsSync(eventPath)
      ? readFileSync(eventPath, 'utf8').trim().split('\n').filter(Boolean).slice(-12).map(JSON.parse) : [];
    console.log(JSON.stringify({ pair, pendingMessageId: pending?.id ?? null, events }, null, 2));
    return;
  }
  if (!['send', 'reply'].includes(command)) throw new Error(usage);
  if ((values.body === undefined) === (values['body-file'] === undefined)) {
    throw new Error('Supply exactly one of --body or --body-file.');
  }
  if (command === 'reply' && !values.to) throw new Error('reply requires --to <received message UUID>.');
  if (command === 'send' && values.to) throw new Error('Use reply to reference a received message.');
  const body = values['body-file'] ? readFileSync(values['body-file'], 'utf8').replace(/^﻿/, '') : values.body;
  const pair = store.getPair();
  const message = store.prepare(store.caller(), body, command === 'reply' ? values.to : null);
  try {
    if (message.to.tool === 'codex') {
      store.publish(message);
      const result = await execute('powershell.exe', [
        '-NoProfile', '-File', join(directory, 'delivery', 'BridgeQueue.ps1'),
        '-ThreadId', pair.codexId, '-Wake', wakeText(pair.id, message.id),
      ], { windowsHide: true, timeout: 15000 });
      store.event('wake-submitted', { messageId: message.id, output: result.stdout.trim() });
    } else {
      const endpoint = readJson(pair.endpointPath);
      if (endpoint.sessionId !== pair.claudeId) throw new Error('Claude endpoint identity changed.');
      const wirePath = join(store.root, 'wire', `${message.id}.txt`);
      writeFileSync(wirePath, renderPeer(message), { flag: 'wx' });
      await execute('powershell.exe', [
        '-NoProfile', '-File', join(directory, 'delivery', 'Send-ClaudePipe.ps1'),
        '-EndpointPath', pair.endpointPath, '-ReplyThreadId', pair.codexId,
        '-MessageFile', wirePath, '-MessageId', message.id,
        '-RecordPath', join(store.root, 'wire', `${message.id}.send.json`),
      ], { windowsHide: true, timeout: 15000 });
      store.event('pipe-written', { messageId: message.id });
    }
  } catch (error) {
    store.event('send-error', { messageId: message.id, error: error.message });
    throw new Error(`Message ${message.id}: ${error.message}. Inspect status before retrying; it may already be pending or consumed.`);
  }
  console.log(JSON.stringify({ messageId: message.id, conversationId: message.conversationId, to: message.to, submitted: true, receipt: 'unverified' }));
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  main().catch((error) => {
    process.stderr.write(`Bridge error: ${error.message}\n`);
    process.exitCode = 1;
  });
}
