import { execFile } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, readdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { promisify, parseArgs } from 'node:util';
import { atomicWriteJson, BridgeStore, handleHook, readJson, renderPeer, wakeText } from './store.mjs';
import { listSessions, selectSession, sessionsDir } from './sessions.mjs';
import { bindThreadRoot, locateMessage, otherRootsServing, resolveRoot } from './roots.mjs';
import { cliPath, commandString, repoRoot } from './entry.mjs';

// Sprint 04 / PBI-11: connect upserts into a multi-pair registry, codex sends
// take an explicit --name target (the single-target 1.0.0 shape without --name
// keeps working), replies resolve their pair from the referenced message,
// retire is the explicit lifecycle boundary, and status lists every pair.

const execute = promisify(execFile);
const directory = fileURLToPath(new URL('.', import.meta.url));
const usage = 'Use one of: install, register, pair, connect, sessions, send, reply, status, hook.';

const HOOK_EVENTS = [
  { event: 'PostToolUse', options: { additionalContextLimit: 20000 } },
  { event: 'UserPromptSubmit', options: { additionalContextLimit: 20000 } },
  { event: 'Stop', options: {} },
];

// Recognizes this product's hook (and the retired prototype's) so installs stay
// idempotent across reinstalls and location changes without touching other tools.
const isBridgeHook = (hook) => typeof hook?.command === 'string' &&
  /(?:bridge[\\/]+cli\.mjs|Bridge\.mjs)"\s+hook$/i.test(hook.command.trim());

function installHooks(hooksFile) {
  const bridgeCommand = `${commandString()} hook`;
  let config = { description: 'ClaudeToCodex cross-session bridge hooks. Generated by `bridge install`.', hooks: {} };
  if (existsSync(hooksFile)) {
    config = readJson(hooksFile);
    if (typeof config !== 'object' || config === null) throw new Error('Existing hooks file is not a JSON object.');
    config.hooks ??= {};
  }
  for (const { event, options } of HOOK_EVENTS) {
    const existing = Array.isArray(config.hooks[event]) ? config.hooks[event] : [];
    const kept = existing.filter((group) => !(Array.isArray(group?.hooks) && group.hooks.some(isBridgeHook)));
    kept.push({ hooks: [{ type: 'command', command: bridgeCommand, timeout: 5, async: false, ...options }] });
    config.hooks[event] = kept;
  }
  mkdirSync(dirname(hooksFile), { recursive: true });
  writeFileSync(hooksFile, `${JSON.stringify(config, null, 2)}\n`);
  console.log(`Hooks file: ${hooksFile}`);
  console.log(`Bridge hook command: ${bridgeCommand}`);
  console.log('Manual steps that cannot be automated:');
  console.log('  1. In the Codex session run /hooks, review and trust the three new bridge hook definitions (a changed definition invalidates its trust hash and must be re-trusted).');
  console.log('  2. Hooks are not hot-loaded: fully exit the running Codex session, then `codex resume <threadId>` to reload with the new hooks.');
  console.log('  3. Claude-side inbound policy: crossSessionInbound holds foreign messages for approval by default; `accept` is the verified configuration. This product never changes that setting.');
}

async function main() {
  const { positionals, values } = parseArgs({
    allowPositionals: true,
    options: {
      codex: { type: 'string' }, 'claude-endpoint': { type: 'string' },
      body: { type: 'string' }, 'body-file': { type: 'string' }, to: { type: 'string' },
      'hooks-file': { type: 'string' }, name: { type: 'string' }, 'sessions-dir': { type: 'string' }, pairId: { type: 'string' },
    },
  });
  const [command] = positionals;
  if (positionals.length !== 1) throw new Error(usage);
  // Root resolution (Sprint 05 / PBI-15): the product flows serve the root that
  // belongs to the calling Codex original session - explicit CTC_BRIDGE_DIR,
  // then an index binding, then the default root when free or already this
  // session's. The low-level manual paths (install, register, pair, sessions)
  // keep the plain default root with its CTC_BRIDGE_DIR override, exactly as
  // documented since 1.0.0.
  const sessionStore = () => new BridgeStore(resolveRoot({ threadId: process.env.CODEX_THREAD_ID ?? null }).root);
  let store = new BridgeStore();
  if (command === 'hook') {
    let input = '';
    for await (const chunk of process.stdin) input += chunk;
    const event = JSON.parse(input);
    store = new BridgeStore(resolveRoot({ threadId: event.session_id ?? null }).root);
    process.stdout.write(`${JSON.stringify(handleHook(store, event, locateMessage))}\n`);
    return;
  }
  if (command === 'install') {
    installHooks(values['hooks-file'] ? resolve(values['hooks-file']) : join(repoRoot(), '.codex', 'hooks.json'));
    return;
  }
  if (command === 'register') {
    store.initialize();
    const result = await execute('powershell.exe', [
      '-NoProfile', '-File', join(directory, 'delivery', 'Register-ClaudeEndpoint.ps1'),
      '-Directory', join(store.root, 'endpoints'),
    ], { windowsHide: true, timeout: 15000 });
    process.stdout.write(`${result.stdout.trim()}\n`);
    return;
  }
  if (command === 'pair') {
    if (!values.codex || !values['claude-endpoint']) throw new Error('pair requires --codex and --claude-endpoint.');
    console.log(JSON.stringify(store.pair(values.codex, values['claude-endpoint'], values.name ?? null), null, 2));
    return;
  }
  if (command === 'sessions') {
    const rows = listSessions(values['sessions-dir'] ? resolve(values['sessions-dir']) : sessionsDir())
      .map(({ name, sessionId, status, alive, hasKey, cwd }) => ({ name, sessionId, status, alive, hasKey, cwd }));
    console.log(JSON.stringify(rows, null, 2));
    return;
  }
  if (command === 'connect') {
    if (!values.name) throw new Error('connect requires --name <part of the Claude session name>.');
    const registry = values['sessions-dir'] ? resolve(values['sessions-dir']) : sessionsDir();
    const session = selectSession(values.name, registry);
    const codexId = process.env.CODEX_THREAD_ID;
    if (!codexId || !/^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$/i.test(codexId)) {
      throw new Error('connect must run inside the selected Codex session (CODEX_THREAD_ID missing).');
    }
    // Root selection for THIS Codex session (S05-15): an index binding is
    // reused; the default root is adopted when it serves nobody or already
    // serves this session (incumbent adoption - no data moves); a default root
    // owned by another Codex steers this session to its own per-thread root.
    // The binding is append-only: one root per Codex session, never rebound.
    const resolution = resolveRoot({ threadId: codexId });
    store = new BridgeStore(resolution.root);
    // Synthesize the endpoint from the session registry: same-user DPAPI wrapping of
    // the registry peer key, so the Claude side never registers anything manually.
    // Registry key files are JSON ({peerToken, procStartFt, pidDomain}); only the
    // peerToken authenticates to the host pipe. The token travels via process
    // environment, never the command line, and error paths never echo it.
    const keyFile = readdirSync(registry).find((f) => f.startsWith(`${session.pid}.`) && f.endsWith('.key'));
    let keyRecord;
    try {
      keyRecord = JSON.parse(readFileSync(join(registry, keyFile), 'utf8'));
    } catch {
      throw new Error(`Peer key file for pid ${session.pid} is not the expected registry JSON record.`);
    }
    const token = typeof keyRecord?.peerToken === 'string' ? keyRecord.peerToken.trim() : '';
    if (!token) throw new Error(`Peer key record for pid ${session.pid} has no peerToken field.`);
    let protectedToken;
    try {
      protectedToken = (await execute('powershell.exe', [
        '-NoProfile', '-Command',
        '$env:CTC_PEER_KEY | ConvertTo-SecureString -AsPlainText -Force | ConvertFrom-SecureString',
      ], { windowsHide: true, timeout: 15000, env: { ...process.env, CTC_PEER_KEY: token } })).stdout.trim();
    } catch (error) {
      throw new Error('DPAPI protection of the peer key failed; no key material is included in this message.');
    }
    if (!protectedToken) throw new Error('DPAPI protection returned an empty token.');
    store.initialize();
    const endpointPath = join(store.root, 'endpoints', `claude-${session.sessionId}.json`);
    // Atomic temp+rename publish: a concurrent reader always sees the complete
    // previous or complete new endpoint record, never a truncated file.
    atomicWriteJson(endpointPath, {
      schema: 1,
      sessionId: session.sessionId,
      socket: session.socket,
      tokenProtected: protectedToken,
      registeredAt: new Date().toISOString(),
      cwd: session.cwd ?? null,
      origin: 'connect-synthesis',
    });
    // Upsert into the multi-pair registry: same Claude session reuses its pair
    // (endpoint refresh allowed); a different one becomes an additional target.
    // Existing pairs are never touched, so connecting B never disturbs A.
    const pair = store.pair(codexId, endpointPath, session.name);
    // Registering the root binding only after a successful pairing keeps a
    // failed connect from claiming a per-thread root; a first successful
    // connect leaves the traceability record S05-15-4 asks for. An explicit
    // CTC_BRIDGE_DIR is an isolation override: it bypasses the index for
    // resolution and must not write it either, or isolated runs would leak
    // bindings into the machine index (and collide with each other).
    if (resolution.source !== 'env') {
      const binding = bindThreadRoot(codexId, store.root);
      if (binding.changed) store.event('root-bound', { codexId, root: store.root, source: resolution.source, index: binding.index });
    }
    store.event('connect', { pairId: pair.id, claudeSession: session.sessionId, claudeName: session.name, codexId: pair.codexId, endpoint: endpointPath });
    console.log(JSON.stringify({ pair, bridgeRoot: store.root, claudeSession: { sessionId: session.sessionId, name: session.name, status: session.status }, hint: `Send with: node "${cliPath()}" send --name <target> --body "..."` }, null, 2));
    return;
  }
  if (command === 'retire') {
    if (!values.pairId && !values.name) throw new Error('retire requires --pairId <uuid> or a unique --name.');
    store = sessionStore();
    const pair = values.pairId ? store.pairById(values.pairId) : store.resolveTarget(values.name);
    if (!pair) throw new Error('No registered pair matches.');
    console.log(JSON.stringify(store.retire(pair.id), null, 2));
    return;
  }
  if (command === 'status') {
    const resolution = resolveRoot({ threadId: process.env.CODEX_THREAD_ID ?? null });
    store = new BridgeStore(resolution.root);
    const pairs = store.pairs().map((pair) => {
      const pendingPath = join(store.root, 'pending', pair.id, 'message.json');
      const pending = existsSync(pendingPath) ? readJson(pendingPath) : null;
      // Project context comes from the endpoint's recorded cwd (S04-11-1);
      // endpointOnDisk only says the registration file exists - it is NOT a
      // process-alive or reachability claim, and none is implied here.
      let project = null;
      if (existsSync(pair.endpointPath)) {
        try { project = readJson(pair.endpointPath).cwd ?? null; } catch { project = null; }
      }
      // Honest pending state (S05-15-5): a published letter with no receipt is
      // simply unclaimed so far. The note names data-plane facts when there are
      // any (another known root also serving this Codex session) and labels
      // everything else possible/unknown - a hook that was never trusted or
      // reloaded cannot be detected from here, and nothing here is a receipt.
      let pendingClaimed = null;
      let pendingNote = null;
      if (pending) {
        pendingClaimed = existsSync(join(store.root, 'receipts', `${pending.id}.json`));
        if (!pendingClaimed) {
          const others = otherRootsServing(pair.codexId, store.root);
          pendingNote = `Published, no claim record yet.${others.length > 0 ? ` Data-plane fact: ${others.length === 1 ? 'another known root also' : `${others.length} other known roots`} serve this Codex session (${others.join('; ')}).` : ''} If it stays pending, possible causes - not detected from here: the receiving Codex session has not trusted/reloaded the bridge hooks since install, or it is running under a different bridge root. Check /hooks, then fully exit and resume the session.`;
        }
      }
      return {
        pairId: pair.id, target: pair.claudeName ?? null, claudeId: pair.claudeId, codexId: pair.codexId,
        createdAt: pair.createdAt ?? null, project, endpoint: pair.endpointPath, endpointOnDisk: existsSync(pair.endpointPath),
        pendingMessageId: pending?.id ?? null, pendingClaimed, pendingNote,
      };
    });
    const eventPath = join(store.root, 'events.jsonl');
    const events = existsSync(eventPath)
      ? readFileSync(eventPath, 'utf8').trim().split('\n').filter(Boolean).slice(-12).map(JSON.parse) : [];
    console.log(JSON.stringify({
      // Which root this status reads (S05-15-4): the resolved serving root,
      // how it was chosen, and the Codex session context - an explicit env
      // source means an isolation override, not an indexed product root.
      root: { path: store.root, source: resolution.source, codexThread: process.env.CODEX_THREAD_ID ?? null },
      pairs, events,
    }, null, 2));
    return;
  }
  if (!['send', 'reply'].includes(command)) throw new Error(usage);
  if ((values.body === undefined) === (values['body-file'] === undefined)) {
    throw new Error('Supply exactly one of --body or --body-file.');
  }
  if (command === 'reply' && !values.to) throw new Error('reply requires --to <received message UUID>.');
  if (command === 'send' && values.to) throw new Error('Use reply to reference a received message.');
  const body = values['body-file'] ? readFileSync(values['body-file'], 'utf8').replace(/^﻿/, '') : values.body;
  // Pair resolution before any body is written: replies bind to the pair of the
  // message they answer (S04-11-3); codex sends name an explicit target
  // (S04-11-2); claude sends resolve through their own session identity. There
  // is no "current" or "most recent" target anywhere on this path.
  store = sessionStore();
  const who = store.caller();
  let pair;
  if (command === 'reply') {
    let previous;
    try {
      previous = store.message(values.to);
    } catch (error) {
      if (error.code === 'ENOENT') {
        throw new Error('No bridge message with that id exists in this data root. Use the reply entry embedded in the message you received (it carries the exact id); run status to inspect recent messages.');
      }
      throw error;
    }
    pair = store.pairById(previous.pairId);
    if (!pair) throw new Error('The referenced message does not belong to any registered pair.');
  } else if (who.tool === 'codex') {
    // 1.0.0 compatibility (S04-11-7): with exactly one connected target, send
    // works without --name exactly as before. No guessing: zero or several
    // targets without a name is an explicit error listing the options.
    if (!values.name) {
      const pairs = store.pairs();
      if (pairs.length === 1) {
        pair = pairs[0];
      } else if (pairs.length === 0) {
        throw new Error('No connected target. Run connect first, or pass --name.');
      } else {
        throw new Error(`send from Codex requires --name <connected target>: ${pairs.length} targets are connected. Run status to list them.`);
      }
    } else {
      pair = store.resolveTarget(values.name);
    }
  } else {
    pair = store.findPairByClaude(who.sessionId);
  }
  const message = store.prepare(pair, who.tool, body, command === 'reply' ? values.to : null, who.sessionId);
  try {
    if (message.to.tool === 'codex') {
      store.publish(message);
      const result = await execute('powershell.exe', [
        '-NoProfile', '-File', join(directory, 'delivery', 'BridgeQueue.ps1'),
        '-ThreadId', pair.codexId, '-Wake', wakeText(pair.id, message.id),
      ], { windowsHide: true, timeout: 15000 });
      store.event('wake-submitted', { messageId: message.id, output: result.stdout.trim() });
    } else {
      const endpoint = readJson(pair.endpointPath);
      if (endpoint.sessionId !== pair.claudeId) throw new Error('Claude endpoint identity changed.');
      const wirePath = join(store.root, 'wire', `${message.id}.txt`);
      // codexHome passes through when this send runs inside an isolated-home
      // Codex session, so the peer's reply wake reaches the right session.
      writeFileSync(wirePath, renderPeer(message, store.root, process.env.CODEX_HOME ?? null), { flag: 'wx' });
      await execute('powershell.exe', [
        '-NoProfile', '-File', join(directory, 'delivery', 'Send-ClaudePipe.ps1'),
        '-EndpointPath', pair.endpointPath, '-ReplyThreadId', pair.codexId,
        '-MessageFile', wirePath, '-MessageId', message.id,
        '-RecordPath', join(store.root, 'wire', `${message.id}.send.json`),
      ], { windowsHide: true, timeout: 15000 });
      store.event('pipe-written', { messageId: message.id });
    }
  } catch (error) {
    store.event('send-error', { messageId: message.id, error: error.message });
    throw new Error(`Message ${message.id}: ${error.message}. Inspect status before retrying; it may already be pending or consumed.`);
  }
  console.log(JSON.stringify({ messageId: message.id, conversationId: message.conversationId, pairId: message.pairId, to: message.to, submitted: true, receipt: 'unverified' }));
}

if (process.argv[1] && pathToFileURL(resolve(process.argv[1])).href === import.meta.url) {
  main().catch((error) => {
    process.stderr.write(`Bridge error: ${error.message}\n`);
    process.exitCode = 1;
  });
}
